version: 1'
services:
    sql:
        container_name: dx-sveltekit-starter
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "dxuser"
            MYSQL_PASSWORD: "secret"
            MYSQL_DATABASE: "dx-sveltekit-starter"
        volumes:
            - dx-sveltekit-starter-data:/var/lib/mysql
        ports:
            - 3307:3306
volumes:
    dx-sveltekit-starter-data: {}
